/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package futoshikiproject;

import Solution.SolveProblem;
import csp.ST;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author DAROUYc
 */
public class ChooseAlgo extends javax.swing.JFrame {

    /**
     * Creates new form ChooseAlgo
     */
    
    //variables
    int dimension;
    JTextField[][]  grille; 
    SolveProblem sc; 
    JPanel grillePn;
    public ChooseAlgo() {
      
        initComponents();
    }
    public ChooseAlgo(int dimension, JTextField [][] grille, SolveProblem sc,JPanel grillePn) {
         initComponents();
         // center JFrame
         setLocationRelativeTo(null);
         // Initialize values
        this.dimension = dimension;
        this.grille = grille;
        this.sc = sc;
        this.grillePn = grillePn;
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboVariableChoice = new javax.swing.JComboBox<>();
        domainCombo = new javax.swing.JComboBox<>();
        amelCombo = new javax.swing.JComboBox<>();
        chooseBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboVariableChoice.setBackground(new java.awt.Color(0, 102, 102));
        comboVariableChoice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboVariableChoice.setForeground(new java.awt.Color(255, 255, 255));
        comboVariableChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Degree", "MRV" }));
        comboVariableChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVariableChoiceActionPerformed(evt);
            }
        });

        domainCombo.setBackground(new java.awt.Color(0, 102, 102));
        domainCombo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        domainCombo.setForeground(new java.awt.Color(255, 255, 255));
        domainCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "LCV" }));

        amelCombo.setBackground(new java.awt.Color(0, 102, 102));
        amelCombo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        amelCombo.setForeground(new java.awt.Color(255, 255, 255));
        amelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forward checking", "AC-1" }));

        chooseBtn.setBackground(new java.awt.Color(153, 153, 0));
        chooseBtn.setForeground(new java.awt.Color(255, 255, 255));
        chooseBtn.setText("OK ");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 121, 181));
        jLabel1.setText("Choose the algorithm to solve");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amelCombo, 0, 152, Short.MAX_VALUE)
                    .addComponent(domainCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboVariableChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboVariableChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(domainCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(amelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(chooseBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboVariableChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVariableChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVariableChoiceActionPerformed

    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBtnActionPerformed
        // TODO add your handling code here:
        
        //get Algorithm 
        ArrayList<String> choice = new ArrayList<>();
        choice.add((String) comboVariableChoice.getSelectedItem());
        choice.add((String) domainCombo.getSelectedItem());
        choice.add((String) amelCombo.getSelectedItem());
        
        // get result 
         ST<String, String> result=sc.solve(choice); 
                if(result!=null)
        {
            // Display result
            for (int i = 0; i < dimension; i++) // Line
         {
             System.out.println("");
             for (int j = 0; j < dimension; j++) // Column
             {
                 if (i % 2 == 0 && j % 2 == 0) 
                 {
                     grille[i * 2][j * 2].setText(result.get("x" + i + "" + j));
                     grille[i * 2][j * 2].setEditable(false);
                 } else if (i % 2 == 0 && j % 2 != 0) 
                 {
                     grille[i * 2][j * 2].setText(result.get("x" + i + "" + j));
                     grille[i * 2][j * 2].setEditable(false);
                 } else if (i % 2 != 0 && j % 2 == 0) 
                 {
                     grille[i * 2][j * 2].setText(result.get("x" + i + "" + j));
                     grille[i * 2][j * 2].setEditable(false);
                 } else if (i % 2 != 0 && j % 2 != 0) 
                 {
                     grille[i * 2][j * 2].setText(result.get("x" + i + "" + j));
                     grille[i * 2][j * 2].setEditable(false);
                 }
                System.out.print(result.get("x" + i + "" + j) + " ");
             }
         } 
         grillePn.repaint();
        }else{
        System.out.println("pas de solution");
        }
                //disappear ChooseAlgo JFrame
                dispose();
    }//GEN-LAST:event_chooseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseAlgo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> amelCombo;
    private javax.swing.JToggleButton chooseBtn;
    private javax.swing.JComboBox<String> comboVariableChoice;
    private javax.swing.JComboBox<String> domainCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
